SELECT [CustomerTransactionID]
      ,[CustomerID]
      ,[TransactionTypeID]
      ,[InvoiceID]
      ,[PaymentMethodID]
      ,[TransactionDate]
      ,[AmountExcludingTax]
      ,[TaxAmount]
      ,[TransactionAmount]
      ,[OutstandingBalance]
      ,[FinalizationDate]
      ,[IsFinalized]
      ,[LastEditedBy]
      ,[LastEditedWhen]
FROM {table_name};