(SELECT [StateProvinceID]
      ,[StateProvinceCode]
      ,[StateProvinceName]
      ,[CountryID]
      ,[SalesTerritory]
      ,[Border]
      ,[LatestRecordedPopulation]
      ,[LastEditedBy]
      ,CAST([ValidFrom] AS VARCHAR(30)) AS [ValidFrom]
      ,CAST([ValidTo] AS VARCHAR(30)) AS [ValidTo]
FROM [WideWorldImporters].[Application].[StateProvinces_Archive]
WHERE ValidFrom <> ValidTo)
union all
(SELECT [StateProvinceID]
      ,[StateProvinceCode]
      ,[StateProvinceName]
      ,[CountryID]
      ,[SalesTerritory]
      ,[Border]
      ,[LatestRecordedPopulation]
      ,[LastEditedBy]
      ,CAST([ValidFrom] AS VARCHAR(30)) AS [ValidFrom]
      ,CAST([ValidTo] AS VARCHAR(30)) AS [ValidTo]
FROM [WideWorldImporters].[Application].[StateProvinces]
WHERE ValidFrom <> ValidTo)