SELECT [SupplierTransactionID]
      ,[SupplierID]
      ,[TransactionTypeID]
      ,[PurchaseOrderID]
      ,[PaymentMethodID]
      ,[SupplierInvoiceNumber]
      ,[TransactionDate]
      ,[AmountExcludingTax]
      ,[TaxAmount]
      ,[TransactionAmount]
      ,[OutstandingBalance]
      ,[FinalizationDate]
      ,[IsFinalized]
      ,[LastEditedBy]
      ,[LastEditedWhen]
FROM {table_name};