/*
Author: Phan Quốc Trung (TrungPQ20)
Database: WideWorldImporters
Module: TRANSACTION
Last Modified When: 14/3/2024
Contributed Bronze table: TransactionTypes
Silver table: TransactionType
*/
-- Delete all data from the table TRANSACTION.TRANSACTION_SILVER.TRANSACTIONTYPE if it exists
TRUNCATE TABLE IF EXISTS TRANSACTION.TRANSACTION_SILVER.TRANSACTIONTYPE;
-- Insert data from the table TRANSACTION.TRANSACTION_BRONZE.TRANSACTIONTYPES into the table TRANSACTION.TRANSACTION_SILVER.TRANSACTIONTYPE
INSERT INTO TRANSACTION.TRANSACTION_SILVER.TRANSACTIONTYPE (
    TRANSACTIONTYPEKEY,
    WWITRANSACTIONTYPEID,
    TRANSACTIONTYPE,
    VALIDFROM,
    VALIDTO
)
SELECT
    CONCAT(TRANSACTIONTYPEID,TO_CHAR(VALIDFROM,'YYYYMMDDHH24MISSFF7')) AS TRANSACTIONTYPEKEY,
    TRANSACTIONTYPEID AS WWITRANSACTIONTYPEID,
    TRANSACTIONTYPENAME AS TRANSACTIONTYPE,
    VALIDFROM AS VALIDFROM,
    VALIDTO AS VALIDTO
FROM
    TRANSACTION.TRANSACTION_BRONZE.TRANSACTIONTYPES

